uploads = []
generated = []

[[outputs]]
id = "ifkFoZ9Biavg0uWrNBohs"
uri = "file://pont-consultoria-github-pages.tar.gz"
type = "unspecified"
title = "Pont Consultoria — Arquivos para GitHub Pages"

[[outputs]]
id = "cevxISxgCsc6pvb22w3tg"
uri = "file://pont-consultoria-github-pages.zip"
type = "unspecified"
title = "Pont Consultoria — GitHub Pages v5 (final)"

[[outputs]]
id = "Rjj0SYCpXwQJWR76fNiim"
uri = "file://artifacts/catluc/public/pont-consulting-favicon.png"
type = "image"
title = "Favicon - Logo Pont Consulting"
